### ISSUE TITLE
Check the entire magic number

### ISSUE THREAD

**Issue by paulmelnikow** [sindresorhus/is-png#2]
Hi there, I use a bunch of your libraries. This may be my first time opening an issue. Thanks for allllll your hard work! 😄 

I was just refactoring [some code in badges/shields](https://github.com/badges/shields/blob/3febfe234ed2f9b4932da4d6bcaa54a18bd02ce7/test/test.spec.js#L62-L69) which checks the PNG magic number.

It looks like this library is checking the first four bytes, instead of the first eight. Is there any reason not to check [the entire signature](https://www.w3.org/TR/PNG/#5PNG-file-signature)?

**Comment by sindresorhus** [comment]
I think it's because many places on the web shows only the first 4 bytes, and I got it from one of those sites. I guess it doesn't hurt to check them all though.
