### ISSUE TITLE
Hypothetical question

### ISSUE THREAD

**Issue by m-onz** [sindresorhus/is-png#4]
Hey,

Thanks for making this library!

This is just a hypothetical question but is it possible to trick this check by providing a valid png signature but using a polyglot file?

related article: https://motherboard.vice.com/en_us/article/qkv53v/how-you-can-get-hacked-just-by-looking-at-a-picture-online

**Comment by sindresorhus** [comment]
Sure, this module doesn't check that it's a valid PNG file, only that it has the PNG marker.
